### ISSUE TITLE
Locale settings

### ISSUE THREAD

**Issue by JBPressac** [Daniel-KM/Omeka-plugin-UniversalViewer#26]
Hello,
I installed the 2.4.4 version of the plugin. By default, in the plugin configuration, the _locales of the viewer_ parameter is set to `en-GB:English (GB),fr:French` however, in the settings of the viewer, only English and Cymreag are available.

**Comment by Daniel-KM** [comment]
Cette option n'a effectivement pas d'effet. Je n'ai pas encore trouvé le temps de simplifier le processus, mais pour l'instant, il faut faire la version française et modifier les fichiers de configuration soi-même.

**Comment by JBPressac** [comment]
Bonjour,
J'ai un petit peu de mal à trouver dans quel fichier modifier le paramètre data-locale. Pouvez-vous me donner un indice ? Merci

**Comment by Daniel-KM** [comment]
Il faudrait effectivement refaire une traduction (il y a une trentaine de chaines seulement) et voir si on peut la pousser sur https://github.com/universalviewer/universalviewer.

**Comment by Daniel-KM** [comment]
La traduction est disponible sur https://www.transifex.com/digirati/universal-viewer-1/

**Comment by JBPressac** [comment]
Bonjour Daniel,
Pour information, j'ai complété et révisé et la traduction en français de UV sur Transifex. Elle a été [intégrée hier au dépôt officiel de UV sur Github](https://github.com/UniversalViewer/universalviewer/commit/197cc1938c70dd5f8fd4688c672c31c00311e1f5). 

Par ailleurs, j'ai compilé UV sur mon poste de travail avec la traduction en français mais je n'arrive pas à voir quels fichiers doivent être récupérés et intégrés à votre plugin.
Bien à vous,

**Comment by Daniel-KM** [comment]
La mise à jour est intégrée à la version 3.0 d'UV, que j'ai intégrée dans la version 2.6 du plugin.

**Comment by JBPressac** [comment]
merci !
