### ISSUE TITLE
Long-running manifest generation causing cloudflare timeout

### ISSUE THREAD

**Issue by edsilv** [Daniel-KM/Omeka-plugin-UniversalViewer#32]
We have a 237 page book in Omeka and the manifest is taking too long to generate, causing our Cloudflare cache to timeout: https://stackoverflow.com/a/38614438

We've added a custom page rule in Cloudflare to bypass this manifest for the time being. We're using a DigitalOcean Ubuntu VM with 1GB of RAM. Ideally we'd like to use this with Cloudflare to keep our costs down.

Do you know of any way to speed up the manifest generation script? My php is really basic, so any tips are greatly appreciated. 

We're using v2.4.5 of this plugin.

**Comment by Daniel-KM** [comment]
No, I don't know, so some improvements are needed, either to cache the manifest, either to speed the its creation. 

The simpler would be to cache the manifests, and to update it when the item is saved. But even in that case, the first generation will fails. The second way is to write a script and to run it offline. The last way is to improve the creation of the manifest, but you are the first with this issue, and nobody ask me yet. 

I have no issue with some books of 600 pages and more, so this is a material issue and hardware is cheaper than software...

**Comment by edsilv** [comment]
It seems like our only option is to upgrade our DO box to 2 CPUs and 2GB of RAM (the next tier up).
Is this comparable to your setup that allows 600 page manifests? What is the recommended minimum spec for a server? $20 p/m is getting pricey for a hobby project...

**Comment by Daniel-KM** [comment]
There is an option to use the url set in an element in the options of the plugin. So save all your manifests (and update them regularly in the background), and fill this element.
I just updated the plugin (and the module for Omeka S) to use version 3. Maybe it is fixed.
