### ISSUE TITLE
Using UniversalViewer with a Proxy

### ISSUE THREAD

**Issue by wgcowan** [Daniel-KM/Omeka-plugin-UniversalViewer#33]
UV doesn't seem to recognize our proxy. Our proxy is example.proxy.edu and it points to server.indiana.edu:8109. For the location of the manifest file and all the image files in the manifest, UV uses server:8109. Consequently, since the manifest file at https://server:8109/iiif/2049/manifest is never found, the UV just spins and never loads. If I take this manifest url and substitute our proxy, then the manifest does load. If I put this https://example.proxy.edu/iiif/2049/manifest in another field and have UV use that field for the manifest, the player loads but none of the image files do, since they look like this in the manifest, https://server:8109/iiif-img/7607/info.json. The site is at https://orsonwelles.indiana.edu if you want to look. Everything else on the site works fine. 

I have made these changes to bootstrap.php so that the rest of the site uses the proxy:

//$base_url = $base_root .= '://' . preg_replace('/[^a-z0-9-:._]/i', '', $_SERVER['HTTP_HOST']);
$base_url = $base_root .= '://' . preg_replace('/[^a-z0-9-:._]/i', '', 'example.proxy.edu');

Any ideas on why UV doesn't use the proxy but uses server:8109 instead?

Thanks for any help

Will

**Comment by Daniel-KM** [comment]
Instead, could you set the `http_host` directly?

```
$SERVER['HTTP_HOST'] = 'example.proxy.edu';
```

**Comment by Daniel-KM** [comment]
Besides, I updated the plugin (v 2.4.6) and added an option in the config. Is it working fine?

**Comment by wgcowan** [comment]
I knew the solution would be to upgrade. And of course, we’ve got 2.4.4 installed. Thanks for the help.

BTW we did find a work around but would like a better solution. So once again thanks.

Will

**Comment by Daniel-KM** [comment]
There is an option to change the base root of the urls in last versions.
