### ISSUE TITLE
index creation

### ISSUE THREAD

**Issue by JBPressac** [Daniel-KM/Omeka-plugin-UniversalViewer#34]
Hello,
Is it possible ton create an index (as in [this example of UV](http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=35&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb18035723%2Fmanifest&xywh=-944%2C0%2C4118%2C3039), in the CONTENTS left panel) with the plugin ?
Thanks,

**Comment by Daniel-KM** [comment]
Bonjour,

Oui, c'est possible et c'est même activé lorsqu'on affiche les items d'une collection (collections/show). 

Cependant, cela n'est pas disponible par défaut pour les items, car il n'y a pas de format standard pour convertir un champ de métadonnées en index. 

Il faut donc soit utiliser le filtre "uv_manifest", soit modifier le manifest à la main et l'enregistrer, puis mettre l'adresse dans le champ indiqué dans la config du plugin.

**Comment by Daniel-KM** [comment]
La "config du plugin" indiqué ci-dessus est celle de la page plugins (extensions) d'Omeka.

**Comment by JBPressac** [comment]
Bonjour,
Pour information, suite à votre suggestion, j'ai développé un petit plugin [Toc for Universal Viewer](https://github.com/JBPressac/TocForUniversalViewer) pour permettre l'affichage dans UV de la table des matières extraite de fichiers PDF avec le plugin [PDFToc](https://github.com/JBPressac/Plugin-PdfToc) (en lien, la version dupliquée de PDFToc de @symac, qui génère une table des contenus en UTF8, sans entités HTML).
Bien à vous,

**Comment by symac** [comment]
De notre côté on est en train d'adapter le plugin PDFToc pour omeka-s de notre coté. Le dépôt est créé sur https://github.com/bubdxm/Omeka-S-module-PdfToc, @laxav se chargera bientôt de mettre tout cela en ligne.

**Comment by JBPressac** [comment]
Bonjour @Daniel-KM, 
J'ai un petit souci avec mon plugin [TocForUniversalViewer](https://github.com/JBPressac/TocForUniversalViewer/issues/1). J'ai apparemment oublié de gérer les cas où UV est appelé sur les pages des Collections. Question bête: A part créer un test sur la variable `$args` transmise par le filtre `uv_manifest`, comment puis-je savoir si le filtre est appelé à la consultation d'un item ou une collection ? D'ailleurs, existe-t-il une documentation qui décrit ce que contient `$args` ?
Bien à vous,

**Comment by JBPressac** [comment]
Bonjour, J'ai trouvé la réponse à ma question.

**Comment by Daniel-KM** [comment]
Très bien. La réponse se trouvait dans le code...
