### ISSUE TITLE
Erreur dans README.md

### ISSUE THREAD

**Issue by JBPressac** [Daniel-KM/Omeka-plugin-UniversalViewer#35]
Bonjour,
Pour information il y a une erreur dans le fichier README.md:

> To customize the configuration of the plugin, create a directory **universal-folder**

à remplacer par:

> To customize the configuration of the plugin, create a directory **universal-viewer**

**Comment by Daniel-KM** [comment]
Bonjour,

Ok merci, je viens de le corriger.
