### ISSUE TITLE
Image Captions

### ISSUE THREAD

**Issue by level-5** [Daniel-KM/Omeka-plugin-UniversalViewer#38]
hi, i use universalviewer in omeka to present pictures - each picture has it own caption - is there a way to show the different imagecaptions with universalviewer or can i just show the captions for the whole set? Thanks best l5

**Comment by Daniel-KM** [comment]
Each item has its metadata, and the universal viewer displays these metadata. Which caption do you talk about?

**Comment by level-5** [comment]
example - one item has 4 imagefiles - with different captions

**Comment by Daniel-KM** [comment]
The title of the file is used as caption. If there is no title, the file name is used.
