### ISSUE TITLE
viewer not loading on all items/collections

### ISSUE THREAD

**Issue by koumts** [Daniel-KM/Omeka-plugin-UniversalViewer#40]
Hello 

I have installed the latest version on Omeka 2.4.1 and on all items/collections, i am getting a black box. 
For example http://diogeneia.library.upatras.gr/items/play/701 

The chrome console returns the following:

701:144 Uncaught TypeError: Omeka.dropDown is not a function
    at HTMLDocument.<anonymous> (701:144)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.K (jquery.min.js:2)
(anonymous) @ 701:144
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
K @ jquery.min.js:2
bundle.min.js:4 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Function.Deserialiser.parse (bundle.min.js:4)
    at Object.create (bundle.min.js:5)
    at Bootstrapper._loaded (bundle.min.js:9)
    at bundle.min.js:9

Could you please help me?

thanks
Regards
K

**Comment by koumts** [comment]
Any update?

**Comment by koumts** [comment]
I did install the latest omeka 2.6.1 and i did something similar. 
The url is
http://diogeneia.library.upatras.gr/items/play/701

and on chrome i am getting the following. Apparently the image is not loaded. Any suggestion is much appreciated. 

bundle.min.js:4 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.Deserialiser.parse (bundle.min.js:4)
    at Object.create (bundle.min.js:5)
    at Bootstrapper._loaded (bundle.min.js:9)
    at bundle.min.js:9

thanks
Regards
Kostas

**Comment by koumts** [comment]
If i get a trace i can see the following on the header 

150.140.152.107 - - [08/Oct/2018:10:47:47 +0300] "GET /plugins/UniversalViewer/views/shared/javascripts/uv/lib/bundle.min.js HTTP/1.1" 200 345939 "http://diogeneia.library.upatras.gr/plugins/UniversalViewer/views/shared/javascripts/uv/app.html?isHomeDomain=true&isOnlyInstance=true&manifestUri=%CE%93%CE%B9%CE%AC%CE%BD%CE%BD%CE%B7%CF%82%20%CE%94%CE%B7%CE%BC%CE%B1%CE%BA%CF%8C%CF%80%CE%BF%CF%85%CE%BB%CE%BF%CF%82%2C%20%CE%9A%CE%B1%CE%B8%CE%B7%CE%B3%CE%B7%CF%84%CE%AE%CF%82%20%CE%A4%CE%BC%CE%AE%CE%BC%CE%B1%CF%84%CE%BF%CF%82%20%CE%A7%CE%B7%CE%BC%CE%B9%CE%BA%CF%8E%CE%BD%20%CE%9C%CE%B7%CF%87%CE%B1%CE%BD%CE%B9%CE%BA%CF%8E%CE%BD&embedScriptUri=http://diogeneia.library.upatras.gr/plugins/UniversalViewer/views/shared/javascripts/uv/lib/embed.js&embedDomain=diogeneia.library.upatras.gr&domain=diogeneia.library.upatras.gr&isLightbox=false&locale=en-GB:English%20(GB),fr:French&config=/plugins/UniversalViewer/views/public/universal-viewer/config.json&xdm_e=http%3A%2F%2Fdiogeneia.library.upatras.gr%2Fitems%2Fplay%2F701&xdm_c=default5555&xdm_p=4" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

Should it be an issue with locale/encoding? 

thanks
regards
K.

**Comment by koumts** [comment]
I further troubleshoot this and i am getting the following once i request the manifest file. 

2018-10-08T14:05:08+00:00 ERR (3): exception 'Exception' with message 'Failed to get resolution of image #29947 ("https://library.upatras.gr/diogeneia2/omeka-2.6.1/files/thumbnails/a948e7b90694e93a3bb31579049a73d7.jpg").' in /var/www/html/diogeneia2/omeka-2.6.1/plugins/UniversalViewer/views/helpers/IiifManifest.php:988
Stack trace:
#0 /var/www/html/diogeneia2/omeka-2.6.1/plugins/UniversalViewer/views/helpers/IiifManifest.php(434): UniversalViewer_View_Helper_IiifManifest->_getImageSize(Object(File), 'thumbnail')
#1 /var/www/html/diogeneia2/omeka-2.6.1/plugins/UniversalViewer/views/helpers/IiifManifest.php(593): UniversalViewer_View_Helper_IiifManifest->_iiifThumbnail(Object(File))
#2 /var/www/html/diogeneia2/omeka-2.6.1/plugins/UniversalViewer/views/helpers/IiifManifest.php(203): UniversalViewer_View_Helper_IiifManifest->_iiifCanvasImage(Object(File), 1)
#3 /var/www/html/diogeneia2/omeka-2.6.1/plugins/UniversalViewer/views/helpers/IiifManifest.php(20): UniversalViewer_View_Helper_IiifManifest->_buildManifestItem(Object(Item))
#4 [internal function]: UniversalViewer_View_Helper_IiifManifest->iiifManifest(Object(Item))
#5 /var/www/html/diogeneia2/omeka-2.6.1/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#6 /var/www/html/diogeneia2/omeka-2.6.1/plugins/UniversalViewer/controllers/PresentationController.php(120): Zend_View_Abstract->__call('iiifManifest', Array)
#7 /var/www/html/diogeneia2/omeka-2.6.1/plugins/UniversalViewer/controllers/PresentationController.php(120): Omeka_View->iiifManifest(Object(Item))
#8 /var/www/html/diogeneia2/omeka-2.6.1/application/libraries/Zend/Controller/Action.php(516): UniversalViewer_PresentationController->itemAction()
#9 /var/www/html/diogeneia2/omeka-2.6.1/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('itemAction')
#10 /var/www/html/diogeneia2/omeka-2.6.1/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /var/www/html/diogeneia2/omeka-2.6.1/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#12 /var/www/html/diogeneia2/omeka-2.6.1/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#13 /var/www/html/diogeneia2/omeka-2.6.1/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#14 /var/www/html/diogeneia2/omeka-2.6.1/index.php(23): Omeka_Application->run()
#15 {main}

it seems that the plugin is not able to get the resolution of image.
Any idea?
thanks

**Comment by Daniel-KM** [comment]
Yes, you find the issue. Have you php extensions exif, gd or imagemagick installed on your server?

**Comment by Daniel-KM** [comment]
This issue was related to the server.
