### ISSUE TITLE
how to update UV core 

### ISSUE THREAD

**Issue by mw0000** [Daniel-KM/Omeka-plugin-UniversalViewer#47]
I'm grateful for your Omeka plugins, especially for Universal Viewer. I try to update the basic libraries, generated from the source (https://github.com/UniversalViewer/universalviewer).
How should I put it into the plugin? I tried:

- git clone https://github.com/Daniel-KM/Omeka-plugin-UniversalViewer (2.6.0)
- copy /uv with the newest version of UV to views/shared/javascripts
- composer install

and than put it on the server, but I got error:

Uncaught TypeError: n is not a function
    at uv.js:11
    at Object.execCb (uv.js:1)
    at b.check (uv.js:1)
    at b.<anonymous> (uv.js:1)
    at uv.js:1
    at uv.js:1
    at each (uv.js:1)
    at b.emit (uv.js:1)
    at b.check (uv.js:1)
    at b.enable (uv.js:1)

Is it a proper workflow? Can you just tell if I made a mistake when
joining the elements (uv core library and your plugin)?

**Comment by Daniel-KM** [comment]
Yes, it is the good process to install the library.
Note: since version 2.6, I use a specific repository in order to install it via composer, so the [composer file](https://github.com/Daniel-KM/Omeka-plugin-UniversalViewer/blob/master/composer.json) always load it. So you don't have to run `composer install` if you copy it manually.

**Comment by Daniel-KM** [comment]
I published version 3.0.36 last month, and it works fine with Omeka S, so I'm going to include it in Omeka Classic soon.

**Comment by Daniel-KM** [comment]
You may have to compile uv first, the plugin use only the distributed files of the library

**Comment by Daniel-KM** [comment]
Last version of the UniversalViewer (3.0.36) is included in [version 2.6.0](https://github.com/Daniel-KM/Omeka-plugin-UniversalViewer/releases).
