### ISSUE TITLE
UniversalViewer does not display documents

### ISSUE THREAD

**Issue by HlebHnevashau** [Daniel-KM/Omeka-plugin-UniversalViewer#48]
Hello.
I have a problem -  UniversalViewer does not display documents, shows nothingt.
Example - http://music.nlb.by/items/show/16
Logging enabled - SetEnv APPLICATION_ENV development
There is nothing in the log file application/logs/errors.log 
The following error is in the file /var/log/httpd/error_log:
PHP Notice:  Undefined variable: result in /var/www/html/plugins/UniversalViewer/views/helpers/IiifManifest.php on line 970, referer: http://music.nlb.by/items/show/16

Thanks.

**Comment by Daniel-KM** [comment]
See answer on https://forum.omeka.org/t/universalviewer-does-not-display-documents/11192/2
